### ISSUE TITLE
requirements.txt vs. install_requires within setup.py

### ISSUE THREAD

**Issue by cuducos** [ckan/ckanext-googleanalytics#48]
Hi there,

Is there a specific reason for keeping the dependencies of this Python package in a `requirements.txt` file and not in the `install_requires=[]` part of the `setup.py`?

The way this project is made ignores `requirements.txt` during `pip install -e <repo>`, making it mandatory to do an extra `pip install -r requirements.txt`. If we use `install_requires`,  all dependencies would be handled during `pip install -e <repo>`, simplifying the installation steps.

I would like to have everything handles by `pip` and I can open a PR.

Also, if you think this way is interesting for the project, I can drop both `requirements.txt` and `setup.py` adopting the PEP 517's `pyproject.toml`, which would give even more flexibility with tools like [Poetry](https://python-poetry.org) (such as dependencies and development dependencies). Any thoughts?

**Comment by smotornyuk** [comment]
It's just [common practice ](https://docs.ckan.org/en/2.9/extensions/best-practices.html#add-third-party-libraries-to-requirements-txt)in CKAN project to use requirements file instead of pinning requirements using `install_requires`. Mainly it's done in order to avoid situations when you unable to install a particular set of extensions\packages because of conflicting requirements - you always have a chance to solve conflict manually

**Comment by cuducos** [comment]
Ow, got it! Many thanks, @smotornyuk!
