### ISSUE TITLE
Error - <type 'exceptions.NameError'>: global name 'Authorizer' is not defined

### ISSUE THREAD

**Issue by anibalpacheco** [ckan/ckanext-googleanalytics#5]
Using CKAN master branch

**Comment by augusto-herrmann** [comment]
The change in [the above commit](https://github.com/dadosgovbr/ckanext-googleanalytics/commit/8964f48879483d47cde7b74580c60b22b7511685) was supposed to fix the extension for the then current version of the Analytics API, but I did not submit a PR at the time for some reason and do not even remember whether or not it was working.

Is anyone still even using this extension? If anyone cares, you may pull from my repo, test it and PR. Otherwise I might end up just deleting my local repo.
