### ISSUE TITLE
Switching to Google Analytics 4?

### ISSUE THREAD

**Issue by mmdolbow** [ckan/ckanext-googleanalytics#69]
[Google Analytics 4](https://support.google.com/analytics/answer/10089681) was introduced within the last few years, and I'm curious if any work has been done on this extension to enable a migration to a GA4 property. It appears that it's only set up for the old "Universal Analytics" but I'm a bit out of my depth so hoping this is a quick answer.

**Comment by smotornyuk** [comment]
We started working on it but not much was done. 
If the only thing you need is sending request details to GA, switch to [tag v2.1.1](https://github.com/ckan/ckanext-googleanalytics/tree/v2.1.1)(or `pip install ckanext-googleanalytics[requirements]==2.1.1` and use the `G-*` tracking code from GA4 instead of `UA-*`. It will automatically switch to a different JS for tracking, and that's it. You should see page visits in the GA console from this moment.

**Comment by mmdolbow** [comment]
Thank you for the advice; sending the details to GA is likely going to be good enough for me - we don't have / need a ton of customization. I will give this a shot, much appreciated!

**Comment by MarkCalvert** [comment]
Hi @smotornyuk,

Is there any update on upgrading to Google Analytics 4 (GA4)?
Currently, the Statistics Retrieval from Google Analytics feature will not work for GA4 because it needs to be upgraded to use the new [Google Analytics Data API (GA4)](https://developers.google.com/analytics/devguides/reporting/data/v1) with the python package [Python Client for Analytics Data API](https://github.com/googleapis/python-analytics-data)
This is quite urgent with the pending deadline of Universial Analytics stopping the collection of data on the 1st of July 2023 [Universal Analytics is going away](https://support.google.com/analytics/answer/11583528?sjid=2103260042827435876-AP)

**Comment by MarkCalvert** [comment]
@smotornyuk Okay, we will work on updating the one functionality we need right now for one of our projects which is getting the raw data from GA4 data API in the CLI load command.

**Comment by kikislater** [comment]
This fork seems to have implemented it ...
https://github.com/derilinx/ckanext-googleanalytics/tree/gtm
